version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      expo-ecosystem:
        patterns:
          - "expo*"
          - "react-native*"
          - "@expo/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
